let palabra1= "Este"; 
let palabra2 = "es" ; 
let palabra3 = "un" ; 
let palabra4 = "algoritmo"; 
let palabra5 = "secuencial"; 
console.log(palabra1); 
console.log(palabra2);
console.log(palabra3);
console.log(palabra4);
console.log(palabra5); 